### ISSUE TITLE
WICHTIG: Rust updaten damit CI durchläuft

### ISSUE THREAD

**Issue by SailReal** [htwg-syslab-bsys-ss18/bsys-ss18-template#13]
Auf Travis läuft bereits die aktuelle Rust-Version inkl. dem `rustfmt 0.4.1-stable (7a80726 2018-04-20)`. Dies ist eine aktuellere Version als ihr auf eurem Container im Einsatz habt (falls ihr nicht aktualisiert habt).
Damit die CI-Skripte morgen Abend nicht fehlschlagen (insbesondere `rustfmt` hat sich etwas geändert), müsst ihr lokal euer Rust updaten und die Tests noch mal mit dieser Version ausführen um eventuell neu hinzugekommene Fehler/Warnungen zu sehen.

**Comment by MarkusBuechler** [comment]
Wenn wir jetzt die CI für HW6 durchlaufen lassen bekommen wir rustfmt Warnungen aus HW4 und HW5 angezeigt. Ich denke das ist **nicht** der gewünschte Effekte.
Diese Dateien aus vergangenen HWs liegen ja auf dem Master und sind nun nicht mehr mit aktuellsten rustfmt Version kompatibel, werden aber bei den PullRequest überprüft.

![bildschirmfoto 2018-05-13 um 22 10 26](https://user-images.githubusercontent.com/26607378/39971395-8bc56be4-56fa-11e8-87b6-8f03bee47b87.png)

Wie sollen wir vorgehen ?

**Comment by SailReal** [comment]
@MarkusBuechler da hast du recht, das sollte so nicht sein!

Mit https://github.com/htwg-syslab-bsys-ss18/bsys-ss18-template/commit/4689cca8fb5de32bd18cfcc50197213622e412a8 wird `rustfmt` nur noch für den aktuellsten hw-Ordner ausgeführt. 

__Bitte aktualisiert alle euren `hw6`-Branch.__

**Comment by MarkusBuechler** [comment]
Top jetzt läuft alles durch. 
Danke für den schnellen Fix

**Comment by SailReal** [comment]
Travis nutzt nun die aktuelle 1.26.1 bei der sich unter Anderem auch minimal was an `rustfmt`geändert hat. Bitte aktualisiert deshalb frühzeitig eure Rust-Version damit die CI auch beim nächsten PR duchläuft.
