### ISSUE TITLE
hw6 parallele Tests

### ISSUE THREAD

**Issue by SvenKnabe** [htwg-syslab-bsys-ss18/bsys-ss18-template#14]
Wir haben folgendes Problem. Unsere Tests überprüfen ob die Umgebungsvariable durch den CD Command richtig gesetzt wurde. Jedoch werden die Tests parallel ausgeführt wodurch die Tests teilweise zufällig fehlschlagen. Eine Lösung ist, die Tests mit dem Argument -- --test-threads=1 aufzurufen. Kann man davon ausgehen, dass die Tests auf dem CI-Server ebenfalls mit dem Argument aufgerufen werden?

**Comment by MaximilianDauner** [comment]
Haben das gleiche Problem.

**Comment by DonatJR** [comment]
Bedenkt bitte dass eure Tests so wie sie sind keine guten Unittests darstellen, da sie voneinander abhängig sind. Selbst wenn ihr das Timing-Problem mit sequentieller Abfolge löst kann ein wieso-auch-immer-fehlschlagender Test oder ein Problem beim Zurücksetzen des Verzeichnis alle weiteren Tests die danach kommen beeinflussen, weil ihr euch in einem undefinierten Zustand befindet.

Aufgerufen wird `cargo test` bei Travis nicht mit diesem Flag, wenn die Umgebungsvariable, wie ihr es jetzt schon tut, aber in den Tests gesetzt wird (`env::set_var("RUST_TEST_THREADS", "1");`) dann _sollte_ das auf Travis auch sequentiell ausgeführt werden.  Eine 100%-ige Garantie dafür kann ich aber nicht geben, also probiert es bitte rechtzeitig aus und kommentiert die betroffenen Tests ggf. mit einer entsprechend aussagekräftigen Notiz aus damit wir sie uns händisch ansehen können.

Diese Lösung ist zwar nicht schön aber auf die Schnelle vermutlich die vertretbarste. Besser wäre es für jeden Test eine eigene, unabhängige Umgebung zu nutzen.
