### ISSUE TITLE
--release Modus

### ISSUE THREAD

**Issue by SpurNut** [htwg-syslab-bsys-ss18/bsys-ss18-template#16]
Folgende Fragen werden in task1 gestellt: `Welche Laufzeiten erhalten Sie, wenn Sie --release benutzen?`, `Welche (ungefähre) Abhängigkeit der Laufzeit von der Difficulty können Sie im --release-Mode bestimmen?`. Ist damit der Subcommand `timings` gemeint?

**Comment by DonatJR** [comment]
Nein, damit ist nicht das `--timings`-Flag gemeint, sondern das Unix Tool `time` um das es ja bei der Unteraufgabe geht.
