### ISSUE TITLE
hw8/task1 Laufzeitmessung

### ISSUE THREAD

**Issue by SvenKnabe** [htwg-syslab-bsys-ss18/bsys-ss18-template#18]
In der task1 soll mit der Flag -w angegeben werden, ob der Consumer auf die Producer wartet oder nicht. Mit -v und timings soll die summierte Laufzeit und Loops angegeben werden. Geht jedoch nicht wenn der Consumer nicht auf die Producer wartet. Wie soll die Ausgabe dann aussehen?

**Comment by DonatJR** [comment]
Da ist uns bei der Aufgabenstellung ein Fehler unterlaufen, eigentlich sollte der Parameter `-w` gar nicht mehr in der Aufgabe vorkommen. Es soll immer auf die `Consumer` gewartet werden, damit sollte sich auch eure Frage erübrigen.

Die Aufgabe ist mit einer weiteren Änderung angepasst (#19), ihr könnt eure Repos also aktualisieren.
