### ISSUE TITLE
HW1 Seed

### ISSUE THREAD

**Issue by MarkusBuechler** [htwg-syslab-bsys-ss18/bsys-ss18-template#2]
Zur Frage 8 von simu1:
In dem Python Code wird zufällig entschieden, ob CPU oder IO ausgeführt wird
```python
num_instructions, chance_cpu = int(tmp[0]), float(tmp[1])/100.0
        for i in range(num_instructions):
            if random.random() < chance_cpu:
                self.proc_info[proc_id][PROC_CODE].append(DO_COMPUTE)
            else:
                self.proc_info[proc_id][PROC_CODE].append(DO_IO)
        return
```

In der Frage 8 wird der Seed immer manuell angegeben, was die Ausgaben reproduzierbar macht. Ist dies gewollt oder eine Fangfrage ?
> See if you can predict how the trace will turn out.

verwirrt mich.

**Comment by DonatJR** [comment]
Es ist keine Fangfrage, der Seed wird hier wie du gesagt hast dazu benutzt um die Ausgabe bei mehreren Ausführungen reproduzierbar zu machen. Das ist wichtig um den Unterschied der einzelnen Flags (`IO_RUN_IMMEDIATE` vs `IO_RUN_LATER` und `SWITCH_ON_IO` vs `SWITCH_ON_END`) im zweiten Teil der Frage überhaupt erkennen zu können. Ansonsten wüsste man nicht, ob eine Änderung durch das Setzen eines Flags oder eine andere Zufallsreihenfolge ausgelöst wurde. Es geht in der Frage also eigentlich darum vorauszusagen wie die Flags die Ausgabe ändern, nicht was der Seed für einen Einfluss darauf hat.

**Comment by MarkusBuechler** [comment]
Jetzt ergibt das Sinn für mich. Top, danke für die gute Antwort.
