### ISSUE TITLE
hw8/task1 Laufzeitmessungen

### ISSUE THREAD

**Issue by SvenKnabe** [htwg-syslab-bsys-ss18/bsys-ss18-template#20]
Stehen die 12 Logischen CPU-Kerne, welche unserem Container zugewiesen sind exklusiv uns zur Verfügung, oder laufen darauf auch andere Container? Bei meinen Laufzeitmessungen schwanken die Ergebnisse sehr. Das ist jedoch erst, seit ich auf dem Container die Messungen durch führe.
Danke im Vorraus

**Comment by SailReal** [comment]
Nach Rücksprache mit Herrn Mächtel:

> Was bei Zeit-Messungen insgesamt sehr viel Messungenauigkeiten hervorrufen kann sind 'printf' Ausgaben, insbesondere wenn diese lokal (auf dem Notebook) oder per remote vom Container an den 'user' übers Netzwerk verschickt werden. Daher vermutlich die Schwankungen auf dem Container und andere Werte auf dem Notebook. <br>
> Hintergrund Info: <br>
> Die Container der Studenten sind auf:
> - CPU Units = 3 und
> - CPU limit=2 <br>
> konfiguriert. <br>
> CPU units is a CFS scheduler feature described here (cpu.shares):
  https://www.kernel.org/doc/Documentation/scheduler/sched-design-CFS.txt <br>
> CPU limit refers to 'cfs_period_us' feature described here:
  https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt <br>
> Die Standard Linux Abfrage, die in der Rust Biblithek benutzt wird, kann hier u.U. fehlerhaft sein, und eben alle 'sichtbaren' CPUs anzeigen, auch wenn diese alle nicht benutzt werden dürfen durch die Limitierung der Container.

Lösungsansätze:
> 1. KEINE printf Ausgaben WÄHREND der Messungen, die verfälschen die Ergebnisse und ändern auch - je nach Blockierung der Konsole - die Ausgabe. Die Messergebnisse in einer Datenstruktur im RAM speichern, und diese dann NACH der Messung auslesen bzw. ausgeben.
> 2. Messungen mehrmals wiederholen und daraus dann die Ergebnisse ableiten.

**Comment by mmaechtel** [comment]
Herr Isele hat in allen Container die Anzahl auf 4 CPUs heute morgen (11.6) erhöht, somit also CPU Units = 4
