### ISSUE TITLE
hw8/task3 bzgl. base

### ISSUE THREAD

**Issue by MarkyMarkz** [htwg-syslab-bsys-ss18/bsys-ss18-template#21]
Im Eingabestring soll das Muster und die Ergebnis-ID übergeben werden. Für die Ausführung des 
Proof-Of-Work-Mechanismus brauchen wir jedoch auch die Base, die wir in hw6 auch übergeben haben.
Soll die Base diesmal dann fest im Programm stehen oder geben wir die zusätzlich zu Muster und ID mit?

**Comment by SailReal** [comment]
Stimmt, die Base hätte eigentlich auch mit übergeben werden müssen.

Da es allerdings schon relativ spät ist und das nicht eindeutig genug in der Aufgabenstellung steht, akzeptieren wir auch eine Lösung mit einer festen- oder zufällig generierten Base.

**Comment by MarkyMarkz** [comment]
Alles klar, danke dir.
