### ISSUE TITLE
HW3 Simu1 Aufgabe 6

### ISSUE THREAD

**Issue by odsource** [htwg-syslab-bsys-ss18/bsys-ss18-template#4]
Hi,

in der README steht ja das man anhand des Topbits erkennen kann in welchem Segment eine virtuelle Adresse liegt. Daher kann man bei Aufgabe 6 sehen das alle Adressen in Segment 1 liegen jedoch ist das "Bild" so ausgelegt das z.B. die virtuelle Adresse 73 in Segment 0 liegt. Oder geht es darum auf welches Segment die Adresse dann im physikalischen Speicher gemapped wird? Aber eigentlich sollte die Adresse ja nicht das Segment ändern egal ob virtuell oder physikalisch, oder doch nicht? 
Je nachdem würde sich z.B. für die Adresse 73 eine seg fault oder die physikalische Adresse 352 ergeben.

**Comment by anaaah** [comment]
Hallo,

wie in der Aufgabe gestellt, geht es darum die physischen Adressen zu berechnen. Die Zuordnung der Segmente kann aus der Graphik entnommen werden.

Wie im Buch, werden hier zwei Topbits verwendet, 10 für Segment 0 und 11 für Segment 1. Somit wechseln die Adressen nicht das Segment.
