### ISSUE TITLE
Unklarer Output in ci/run-all.sh

### ISSUE THREAD

**Issue by MarkusBuechler** [htwg-syslab-bsys-ss18/bsys-ss18-template#5]
Hey,
beim ausführen des CI Skripts bin ich auf mysteriöse Outputs gestoßen.

<img width="869" alt="bildschirmfoto 2018-04-16 um 00 29 35" src="https://user-images.githubusercontent.com/26607378/38784146-1db09e50-410e-11e8-8dd3-7cd69f329724.png">
 
Hier konnte ich noch erraten, dass mein Programm die falschen Anführungszeichen ausgibt und der Test fehlschlägt

<img width="619" alt="bildschirmfoto 2018-04-16 um 00 32 26" src="https://user-images.githubusercontent.com/26607378/38784163-57fa1f3c-410e-11e8-9fd5-243856a2c609.png">

Bei dem 7/7 Test habe ich allerdings keine Ahnung was meine Ausgabe ist und gegen was getestet wird.

![bildschirmfoto 2018-04-16 um 00 44 10](https://user-images.githubusercontent.com/26607378/38784237-5dca9af8-410f-11e8-99bd-134d378d3a7e.png)

Mir war bisher nicht bewusst, dass es zusätzliche Tests für die Rust Programme gibt und wo der Sinn dahinter ist, wenn die "normalem" Test mit cargo test nicht ausreichen. Könnt ihr mir verraten, was diese Tests bewirken, speziell der 7/7.

**Comment by DonatJR** [comment]
Der Test prüft ob euer Programm eine einzeilige Ausgabe beim Aufruf mit dem Parameter `a` macht und die Tests dienen zur Prüfung der Formatierung eurer Ausgaben (wohingegen die Rust-Tests die Funktionalität prüfen).

**Comment by MarkusBuechler** [comment]
Ok alles klar, dann haben diese Tests ja ihre Daseinsberechtigung. 
Hilfreich wäre es gewesen, wenn bei den Tests angezeigt wird was denn mein Output ist.
`Expected 1, got 2` zum Beispiel.

Vielleicht gibt es ja so eine Funktionalität in eurem Testframework.
Issue kann dann geschlossen werden

**Comment by MarkusBuechler** [comment]
Ok ich habe auf den StdErr Kanal geschrieben wie es [hier](https://doc.rust-lang.org/std/process/fn.exit.html) angegeben war. wc bzw. xargs lesen standardmäßig nur vom Stdout Kanal. Vllt kann man das für die nächsten Aufgaben berücksichtigen

**Comment by SailReal** [comment]
Wir haben das mit https://github.com/htwg-syslab-rust/bsys-ss18-template-prepare/commit/6654a19eb86445a93161ceb3cb687b65eb1d3069 gefixt und im Template veröffentlicht.

Ihr dürft also ab jetzt im Fehlerfall __sehr__ gerne auf `stderr` schreiben 😉
