### ISSUE TITLE
Rust-Codequalität mit clippy verbessern

### ISSUE THREAD

**Issue by DonatJR** [htwg-syslab-bsys-ss18/bsys-ss18-template#7]
Hinweis an alle: Mit dem Tool [clippy](https://github.com/rust-lang-nursery/rust-clippy) könnt ihr euren Rust-Code analysieren lassen und so schon einmal viele Fehler vorneweg beseitigen bevor ihr ihn zur Bewertung abgebt / den PR stellt. Dies ist keine Pflicht, nimmt euch letztendlich aber einiges an Arbeit bei der Korrekturrunde ab bzw. verhindert unnötigen Punkteabzug. 😉

**Comment by SailReal** [comment]
`Clippy` auf `Crates.io` hat gerade Probleme mit den 1.27er nightlies...wenn ihr bereits ein Update auf eine 1.27er gemacht habt könnt ihr wie folgt vorgehen, damit ihr wieder eine lauffähige `Clippy`-Version bekommt:

1.  Eure nightly updaten mit `rustup update nightly` (ihr braucht min. die `rustc 1.27.0-nightly (66363b288 2018-04-28)`
2. Das Githup-Repo von [clippy](https://github.com/rust-lang-nursery/rust-clippy) klonen
3. In das clippy-Verzeichnis wechseln und clippy mit `cargo +nightly install --force` installieren

Danach könnt ihr es ganz normal mit `cargo +nightly clippy` verwenden...
