### ISSUE TITLE
hw4 task1 unit_test_pstree.rs

### ISSUE THREAD

**Issue by NwieNiki** [htwg-syslab-bsys-ss18/bsys-ss18-template#9]
Hallöchen,

wir sollen ja für unsere Funktionen in pstree.rs geeignete tests schreiben.
Nun weiß ich aber nicht genau wie, da meine Funktionen nichts zurückgeben, sondern nur Teile des Baumes printen.
Der Baum (mit den PIDs) sieht ja bei jedem Aufruf ebenfalls anders aus.
Sogar der init-Prozess kann ja laut README.md unterschiedlichen namen haben.

Bedanke mir schonmal für eure Hilfe ;)

**Comment by SailReal** [comment]
Hey hey,

genau, man könnte die Funktionalität in eine extra Funktion auslagern, eine entsprechende Methode mit Input und Output schreiben, die man dann entsprechend testen kann.

**Comment by NwieNiki** [comment]
Habe jetzt das Problem, dass bei mir keiner der Tests (unit_test_readproc.rs) durchläuft (running 0 tests).
Muss ich an dem File noch was verändern?
Laut Readme sollen wir ja nur für pstree eigene Tests schreiben.

**Comment by SailReal** [comment]
Ihr habt vmtl `mod unit_test_readproc;` __nicht__  in eurer `main.rs` drin?

**Comment by NwieNiki** [comment]
ah hehe daran hat's gelegen :)
